# display settings for QGIS layers
display_study_area: True
display_network: True
display_technical: True
display_evaluation_input: True
display_evaluation_output: True
display_slope: True
display_disconnected_components: True
display_edge_lengths: True
display_loop_lengths: True