# here you can provide custom colors for each layer from the two folders
# `/data/input/point/` and `/data/input/polygon/`
# format: "layername" : "X,Y,Z" 
# where X, Y, Z are the RGB values (see e.g. https://rgbcolorpicker.com)
# for example:
# "nature": "0,128,0"
# unless you provide custom colors for all layers, 
# the BikeNodePlanner will generate colors automatically.