### custom color settings
# here you can edit the default colors for slope visualization
# format: "sloperange" : "X,Y,Z" 
# where 0, a, b, c refers to the corresponding slope range (see config-slope.yml for their values)
# and X, Y, Z are RGB values (see e.g. https://rgbcolorpicker.com)

# SLOPE
slope:
  "slope_0" : "255, 186, 186" #  "#ffbaba"
  "slope_a" : "255, 82, 82" # #ff5252 
  "slope_b":  "255, 0, 0" # #ff0000 
  "slope_c" : "167, 0, 0" # #a70000 